

server:
  port: 4000


spring:
  data:
    mongodb:
      uri: mongodb+srv://Shanksazure:Shashank123@shashankazure.ca869dx.mongodb.net/
      port: 27017
      database: Guard_DB


secrets:
  jwt-secret-key: YYwzirRgOIRLejdymwtcw1IyWlYGVd5sfeIT3807hfPyVTFBqjVIBI7PatO8DLXt

