server:
  port: 6000

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: shashankk.mtoc@gmail.com
    password: zuav femk pgoj efak
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable:true

