server:
  port: 6000

spring:
  mail:
    host: smtp.gmail.com
    username: shashankk.mtoc@gmail.com
    password: dzog vpkr vtnp mdls
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable:true

