
server:
  port: 8002



spring:
  datasource:
    url: jdbc:postgresql://database-pg.czvjklgff5zz.ap-south-1.rds.amazonaws.com:5432/Patient_DB
    driver-class-name: org.postgresql.Driver
    username: postgresAWS
    password: Shashank123



  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  instance:
    prefer-ip-address: true


