server:
  port: 8009

spring:
  datasource:
    url:
      jdbc:mysql://school.cw8b8fejq76v.ap-south-1.rds.amazonaws.com/roomdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234
  jpa:
    hibernate:
      ddl-auto: update

